name: Tauri Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -euxo pipefail
          sudo apt-get update
          # En Ubuntu 24.04 el paquete es libwebkit2gtk-4.1-dev; en 22.04 es libwebkit2gtk-4.0-dev
          sudo apt-get install -y build-essential pkg-config libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev || true
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Install dependencies
        run: npm ci

      - name: Tauri build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: PlumaMD ${{ github.ref_name }}
          releaseBody: 'Version ${{ github.ref_name }} generada automáticamente.'
          releaseDraft: false
          prerelease: false
